//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Planz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xooml:fragment xmlns:xooml=&quot;http://kftf.ischool.washington.edu/xmlns/xooml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://kftf.ischool.washington.edu/xmlns/xooml http://kftf.ischool.washington.edu/XMLschema/0.41/XooML.xsd&quot; schemaVersion=&quot;0.41&quot; itemAddress=&quot;&quot; defaultApplication=&quot;&quot; relatedItem=&quot;&quot;&gt;
        ///  &lt;xooml:fragmentToolAttributes xmlns=&quot;http://kftf.ischool.washington.edu/xmlns/planz&quot; toolVersion=&quot;0.41&quot; toolName=&quot;planz&quot; startDate=&quot;1/1/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_MyFirstProject {
            get {
                return ResourceManager.GetString("Planz_MyFirstProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xooml:fragment xsi:schemaLocation=&quot;http://kftf.ischool.washington.edu/xmlns/xooml http://kftf.ischool.washington.edu/XMLschema/0.41/XooML.xsd&quot; schemaVersion=&quot;0.41&quot; defaultApplication=&quot;&quot; relatedItem=&quot;C:\Users\Sheng Bi\Projects\ee9d38b9-6f6f-4bbe-8f5b-e6515a992a73\&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xooml=&quot;http://kftf.ischool.washington.edu/xmlns/xooml&quot;&gt;
        ///  &lt;xooml:fragmentToolAttributes xmlns=&quot;http://kftf.ischool.washington.edu/xmlns/planz&quot; to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_Notes {
            get {
                return ResourceManager.GetString("Planz_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xooml:fragment xmlns:xooml=&quot;http://kftf.ischool.washington.edu/xmlns/xooml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://kftf.ischool.washington.edu/xmlns/xooml http://kftf.ischool.washington.edu/XMLschema/0.41/XooML.xsd&quot; schemaVersion=&quot;0.41&quot; itemAddress=&quot;&quot; defaultApplication=&quot;&quot; relatedItem=&quot;&quot;&gt;
        ///  &lt;xooml:fragmentToolAttributes xmlns=&quot;http://kftf.ischool.washington.edu/xmlns/planz&quot; toolVersion=&quot;0.41&quot; toolName=&quot;planz&quot; startDate=&quot;&quot; du [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_Root {
            get {
                return ResourceManager.GetString("Planz_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xooml:fragment xmlns:xooml=&quot;http://kftf.ischool.washington.edu/xmlns/xooml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://kftf.ischool.washington.edu/xmlns/xooml http://kftf.ischool.washington.edu/XMLschema/0.41/XooML.xsd&quot; schemaVersion=&quot;0.41&quot; itemAddress=&quot;&quot; defaultApplication=&quot;&quot; relatedItem=&quot;&quot;&gt;
        ///  &lt;xooml:fragmentToolAttributes xmlns=&quot;http://kftf.ischool.washington.edu/xmlns/planz&quot; toolVersion=&quot;0.41&quot; toolName=&quot;planz&quot; startDate=&quot;1/1/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_Today {
            get {
                return ResourceManager.GetString("Planz_Today", resourceCulture);
            }
        }
    }
}
