//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCapture.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickCapture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///  &lt;Element Guid=&quot;e40239dd-426d-49de-b4d2-fd1e17351cbb&quot; Type=&quot;Note&quot; NoteText=&quot;This could be your first project! Replace “My First Project” with the name for your project – just as you might do to change the heading of a document. Shorter is better. “Boston Trip” is better than “Plan trip to Boston next month”.&quot; Status=&quot;Normal&quot; AssociationType=&quot;None&quot; AssociationURI=&quot;&quot; IsExpanded=&quot;False&quot; Highlight=&quot;Black&quot; Tag=&quot;&quot; Extra=&quot;&quot; Discoverable=&quot;False&quot; /&gt;
        ///  &lt;Element Guid= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_MyFirstProject
        {
            get
            {
                return ResourceManager.GetString("Planz_MyFirstProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///  &lt;Element Guid=&quot;32b24fe1-45e3-4965-bfa0-38330dd6864a&quot; Type=&quot;Heading&quot; NoteText=&quot;Today+&quot; Status=&quot;Normal&quot; AssociationType=&quot;Folder&quot; AssociationURI=&quot;Today+&quot; IsExpanded=&quot;True&quot; Highlight=&quot;DarkBlue&quot; Tag=&quot;&quot; Extra=&quot;&quot; Discoverable=&quot;True&quot; /&gt;
        ///  &lt;Element Guid=&quot;9ebe1229-e0f4-4400-b6be-7566da1a2730&quot; Type=&quot;Heading&quot; NoteText=&quot;My first project&quot; Status=&quot;Normal&quot; AssociationType=&quot;Folder&quot; AssociationURI=&quot;My first project&quot; IsExpanded=&quot;True&quot; Highlight=&quot;DarkBlue&quot; Tag=&quot;&quot; Extra=&quot;&quot; Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_Root
        {
            get
            {
                return ResourceManager.GetString("Planz_Root", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///  &lt;Element Guid=&quot;09f75ccb-9134-439e-a333-9dad503fd9b9&quot; Type=&quot;Note&quot; NoteText=&quot;What do you want to do today (or soon)? What do you need to remember? Type in a few words (or numbers) here to help you remember.&quot; Status=&quot;Normal&quot; AssociationType=&quot;None&quot; AssociationURI=&quot;&quot; IsExpanded=&quot;False&quot; Highlight=&quot;Black&quot; Tag=&quot;&quot; Extra=&quot;&quot; Discoverable=&quot;False&quot; /&gt;
        ///  &lt;Element Guid=&quot;e34921c2-96f3-459e-9e3b-ba22b6f1252c&quot; Type=&quot;Note&quot; NoteText=&quot;Press the Enter key to start a new note (on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Planz_Today
        {
            get
            {
                return ResourceManager.GetString("Planz_Today", resourceCulture);
            }
        }
    }
}
